### ISSUE TITLE
Default currency doesn't work correctly with FooBarWidget-money 2.1.3

### ISSUE THREAD

**Issue by jmcnevin** [collectiveidea/acts_as_money#1]
When using something like...

```
money :price
```

The currency for the money object will be set to nil, rather than defaulting to "USD".

**Comment by jmcnevin** [comment]
This is in Rails 2.3.2.  Perhaps the behavior of composed_of has changed?  I've noticed that when no currency is defined you're basically doing :mapping => %w[USD currency], which could cause some odd results.

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
